services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: bm
      POSTGRES_PASSWORD: bm
      POSTGRES_USER: bm
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
