version: '3'

tasks:
  gen:
    - go run github.com/99designs/gqlgen generate --config gqlgen.yml
  mockery:
    - docker run -v "$PWD":/src -w /src vektra/mockery --all
  build:
    - docker build --platform=linux/amd64 --target release -t registry.gitlab.com/??? .
  push:
    - docker push registry.gitlab.com/???:latest
  up:
    - docker stop $(docker ps -a -q) > /dev/null || true
    - docker compose up -d
  migrate:
    - go run . migrate
  watch:
    - gowatch -args bot
  dev:
    - task: up
    - task: migrate
    - task: watch
