package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"bm/api/gen"
	"bm/api/model"
	"context"
	"fmt"
)

// Dosomething is the resolver for the dosomething field.
func (r *mutationResolver) Dosomething(ctx context.Context, in model.Do) (*bool, error) {
	panic(fmt.Errorf("not implemented: Dosomething - dosomething"))
}

// Mutation returns gen.MutationResolver implementation.
func (r *Resolver) Mutation() gen.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
